### ISSUE TITLE
Docker-compose: services stopping, missing configuration file?

### ISSUE THREAD

**Issue by Laurentjg** [opfab/operatorfabric-core#99] opened 2019-09-11 12:39 UTC
_Originally posted by @Laurentjg in https://github.com/opfab/operatorfabric-core/issues/94#issuecomment-528745159_

Hi @HanaeSafiRTE ,
[9f094b7db914log.log](https://github.com/opfab/operatorfabric-core/files/3582686/9f094b7db914log.log)
Actually the "deploy" docker is not working either. It starts up all containers. After a while the keycloack stops, followed by the of-users-business-services and seconds after that much more will stop. The only containers still alive are:
- web-ui
- registry-cloud-service
- rabbitmq
- mongodb

I logged (docker logs [id] > [file])  the users-business-services that stoped as one of the first onces. A developer supported me to find some possible causes in it. It seems that there is a problem with a configuration file at the client for accessing the mongodb.

Caused by: java.lang.NullPointerException: null
                at org.lfenergy.operatorfabric.springtools.configuration.mongo.MongoConfiguration.mongoSettings(MongoConfiguration.java:138) ~[spring-mongo-utilities-0.8.1.SNAPSHOT.jar!/:na]

I just want to spin the docker-compose up to interact with operator fabric and make a mock-up demo system. As I'm not a java developer I unfortunately cannot look deeper into the problem.
For more details I attached the logfile. If there is an easy way to get _Of_ running in one or two hours, please let me know. Do you like me to make a new Issue of it?

**Comment by AlexGuironnetRTE** [comment] 2019-09-19 12:54
Hello @Laurentjg,

Sorry for the late reply, and thank you for all the information you provided, I'm trying to reproduce the issue now.
The "easy way to get OF running" is without delving into the code/deployment management is using this docker-compose... and it used to work fine but we don't use it for development purposes so we didn't notice that it wasn't working for our new releases, we'll make sure to check from now on, sorry again.
I'm going to look into it and hopefully fix the deploy docker-compose, I'll let you know as soon as it's done so you can give it another try.
Don't hesitate if you have any other question in the meantime.

**Comment by AlexGuironnetRTE** [comment] 2019-09-23 12:19
Hello @Laurentjg,

I haven't been able to reproduce your issue so far, but I'm thinking it might be because even though I have the same docker-compose file, maybe the snapshot images it relies on weren't the same?
The thing is that snapshot images get updated every night, so depending on the date when you first ran the docker-compose, the images that were pulled from DockerHub might be quite different from what I'm pulling now.
That made us realise that it's probably better for this docker-compose to rely on the last RELEASE image so we can reproduce any issue more reliably.
There were also other issues with the naming of the containers and the new "action" service was missing, so I fixed that as well.  
Would you mind pulling the latest commit from our repo and running the deploy docker-compose again?

I've tried it myself and here is what you should see:

![image](https://user-images.githubusercontent.com/45459065/65423866-6827f880-de0a-11e9-849b-41f87b723656.png)

docker network ls should show you at least a "deploy_default" network.

Please let me know how that goes! Once all services are running, you can use the following script to push some cards using existing templates for a quick look:

services/core/cards-publication/src/main/bin/push_card_loop.sh

Alternatively, if you can tell me what is the latest commit you had when you launched the docker-compose or when your images are from, I might be able to go back and reproduce the issue.

Looking forward to hearing from you

**Comment by Laurentjg** [comment] 2019-10-08 09:00
Hi Alex,

Both our developer and I did a git clone and after that started all services. Unfortunately (almost) the same behavior. On of the first services that stop within 1 or 2 minutes is of-thirds-business-service. We attached the docker logs of the relevant part. It seems that the services stops without correct error-handling on the missing oauth?

Docker log of feoperatorfabric/of-thirds-business-service:0.9.1.RELEASE:

Method springSecurityFilterChain in org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration required a bean of type 'org.springframework.security.oauth2.jwt.JwtDecoder' that could not be found.

The following candidates were found but could not be injected:
                - Bean method 'jwtDecoderByIssuerUri' in 'OAuth2ResourceServerJwtConfiguration' not loaded because OpenID Connect Issuer URI Condition did not find issuer-uri property
                - Bean method 'jwtDecoderByJwkKeySetUri' in 'OAuth2ResourceServerJwtConfiguration' not loaded because @ConditionalOnProperty (spring.security.oauth2.resourceserver.jwt.jwk-set-uri) did not find property 'spring.security.oauth2.resourceserver.jwt.jwk-set-uri'


Action:

Consider revisiting the entries above or defining a bean of type 'org.springframework.security.oauth2.jwt.JwtDecoder' in your configuration.

**Comment by AlexGuironnetRTE** [comment] 2019-10-09 07:33
Hi Laurent,

Thank you very much for trying again and for this feedback...  That is so weird. My understanding is that the point of using docker-compose and published images is precisely that it should be self-contained and independent from the computer it's running on... but I'm clearly missing something.
I'm going to try it on another computer (with a different OS and not from the OpFab team) to see if I can reproduce.
I'm also going to look into the error message from the log you provided.

I'll get back to you as soon as possible, thanks again!

Alex

PS: I'm grasping at straws here, but I'd rather ask just in case it's relevant: what OS are you and your developer using ? What version of docker/docker compose ?

I'm on Fedora 27 with the following version of docker and docker-compose:

> 
> **guironnetale ~  $ ​docker version**
> WARNING: Error loading config file: /home/guironnetale/.docker/config.json: EOF
> Client:
>  Version:           18.09.0
>  API version:       1.39
>  Go version:        go1.10.4
>  Git commit:        4d60db4
>  Built:             Wed Nov  7 00:48:52 2018
>  OS/Arch:           linux/amd64
>  Experimental:      false
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          18.09.0
>   API version:      1.39 (minimum version 1.12)
>   Go version:       go1.10.4
>   Git commit:       4d60db4
>   Built:            Wed Nov  7 00:19:08 2018
>   OS/Arch:          linux/amd64
>   Experimental:     false

> 
> **guironnetale ~  $ ​docker-compose version**
> docker-compose version 1.17.1, build 6d101fb
> docker-py version: 2.6.1
> CPython version: 3.6.6
> OpenSSL version: OpenSSL 1.1.0i-fips  14 Aug 2018

**Comment by AlexGuironnetRTE** [comment] 2019-10-09 10:13
Hi again,

Just to let you know that I think I've found the problem, so don't bother with the versions. The thing is that the services are relying on some data (especially config data) that is stored in folders that are generated during the build... Which is why it worked for me but not for you as you've never built OpFab (and rightly so as the whole point of this docker is not having to build).

I'll get back to you shortly either with a fixed docker-compose or provide you the missing files as a temporary workaround.

Alex

**Comment by AlexGuironnetRTE** [comment] 2019-10-10 09:24
Hi Laurent,

I've tried the new docker-compose on a brand new cloned repository and it's working for me. Please pull the latest commit and let me know how it goes for you!

Alex

**Comment by Laurentjg** [comment] 2019-10-11 08:37
Hi Alex,
Good news, the services are starting and they are staying up. I can login to the GUI via http://localhost:2002/ui/. 
In fact, I did the same workflow as before and the same workflow the developer did. It seems that I got an update over git-clone that works. 

Just for your information: I noticed that after approx. 2 minutes up-time, my 8-core processor is running at 100%. After approx. another 2 minutes it was going back to normal levels again. It this normal behavior?

I ran the script push_card_loop.sh, but the events were not shown at the dashboard. I see this as a separate issue and will spend some time to see if it is a configuration issue at my side. So for now, the issue of dying services is solved.
Thanks for the support so far!

**Comment by AlexGuironnetRTE** [comment] 2019-10-14 08:31
Hi Laurent,
this is great news! Thanks for trying again!

Well the first 2 minutes sound about right, but I'm more surprised about the additional 2 minutes before going back to normal... 
My computer has an 8-core processor and 32Go RAM, and here's roughly how it goes when I launch the docker-compose:
- Goes to 100% CPU / 11Go RAM almost immediately
- 35s : Eureka Registry is up at localhost:2001 (same CPU/RAM++)
- 1m15s : Config is up and registered with Eureka (same CPU/RAM++)
- 2m20: All services are up and registered with Eureka (same CPU/RAM++)
- 2m40 : RAM stays around 18 Go but CPU goes back to baseline

This is clearly a lot of resources for a demo but that's due to the microservices architecture: on top of the KeyCloak, MongoDB and RabbitMQ containers, each of our 10 services has its own container.
We should be able to reduce that by making hypotheses about what people want from a demo (volume of cards, rate of publication, number of users etc.) and fine-tuning the resources for each service accordingly instead of just using the default, but we haven't gotten around to it yet.

Hum... that's odd, the push_card_loop shouldn't require any configuration... are you logging in using the "admin" user ?

You're very welcome, please don't hesitate if I can help with the troubleshooting!

**Comment by AlexGuironnetRTE** [comment] 2019-10-22 08:24
@Laurentjg 

Hi again Laurent,

I've been able to reproduce your issue with the cards that wouldn't show up in the feed, and I'm very sorry to say that it's an error on our side again... Version 0.9.1.RELEASE contains developments that are still in progress regarding a new mode of authorization, and the accompanying configuration was missing from the docker images. So what you're seeing is that the services are running, the user can log in but his authorizations can't be retrieved, so OpFab can't show anything because it doesn't know what the user has access to.

We apologize for the inconvenience, this is fixed in the 0.10.1.RELEASE images that have just been published to DockerHub so if you pull the latest commits and try again it should finally work!

Please let me know if I can be of help!

**Comment by Laurentjg** [comment] 2019-11-06 18:25
Hi Alex,
I found some time to check it again. Unfortunately bad news and same situation. I did a new git clone, removed all docker images, checked the environmental variables and did the docker-compose up again. But: same behavior. No cards are showing up logged in as admin.
Is there some way I can debug in my situation? A command directly to the localhost:/2102/cards is giving a success as a reply. 
I'm curious if I can help debugging with some tests.

**Comment by AlexGuironnetRTE** [comment] 2019-11-07 20:58
Hi Laurent, 
Thank you for trying again. Unfortunately I've just gotten a new computer so I'm in the process of reinstalling all my development environment, so I didn't have the time to try again and investigate today and now I'm on holiday until Nov 12th.

Off the top of my head, here are a few troubleshooting questions:

1) Are you using the deploy docker-compose + push_card_loop script or the demo docker-compose? I'm asking because when I tried the demo one I noticed that the cards were being pushed with a date in 1970 so you would need to change the date filters in the feed (the little clock button) to see them.

2) Can you see some menu links in the navigation bar apart from Feed and Archive? If so, that's the sign that the authorization problem I was mentioning is indeed fixed because these extra links are retrieved from the thirds service (which requires auth), so that's another problem.

Yes thanks for offering, if you could pull up the "Network" tab in "Developer tools" (at least that's what it's called in Chrome) when you open the application for the first time we could see what requests are fired (and their results) and then I hope my colleagues can look into it!

**Closed** 2020-01-30 16:53 UTC
