### ISSUE TITLE
Error in console while having no pinnedcards

### ISSUE THREAD

**Issue by geppyz** [opfab/operatorfabric-core#4028] opened 2023-01-13 09:37 UTC
We see an error in the browser console when we open the application. This is regarding to pinned cards. We have no pinned cards configured.
<img width="1725" alt="Schermafbeelding 2023-01-13 om 09 26 13" src="https://user-images.githubusercontent.com/18466477/212287438-3cd3a7a8-39f9-42bb-9706-d9d216556cbb.png">

**Comment by quinarygio** [comment] 2023-01-13 14:46
Wich version of OpFab are you using? We solved a similar issue, it should be fixed on develop

**Comment by geppyz** [comment] 2023-01-16 11:00
This problem occurred with running release version 3.11.2.

**Comment by quinarygio** [comment] 2023-01-19 08:43
The issue is solved in current develop branch and the correction will be included in next release

**Closed by quinarygio** 2023-01-19 08:43 UTC
Labels: Bug
