### ISSUE TITLE
How to build Operator Fabric?

### ISSUE THREAD

**Issue by ocou-aprico** [opfab/operatorfabric-core#34] opened 2019-01-10 15:16 UTC
Dear,

I am trying to build OperatorFabric from scratch on Mac OS X using the bin/build_all script but the build stopped by 'Failed to apply plugin [id 'cz.malohlava']'.
Note that I have to uncomment in the main build.gradle file the last lines because gradle complains about the fact that the wrapper task is defined several times.

Here follows the stack trace. 

Thanks for your attention

Olivier Coussaert
Aprico Consultants

Env:
------------------------------------------------------------
Gradle 5.1
------------------------------------------------------------

Build time:   2019-01-02 18:57:47 UTC
Revision:     d09c2e354576ac41078c322815cc6db2b66d976e
Kotlin DSL:   1.1.0
Kotlin:       1.3.11
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_151 (Oracle Corporation 25.151-b12)
OS:           Mac OS X 10.14 x86_64

NB/ realpath from Apple does not behave like the Linux realpath (but can be easily fixed by using brew).

Now the output of bin/build_all.sh :
#### Building artifacts ####
# Using gradle options:   #
## Building swagger generator
+ gradle :tools:swagger-spring-generators:assemble

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/ocouss/operatorFabric/operatorfabric-core/services/services.gradle' line: 32

* What went wrong:
A problem occurred evaluating project ':services'.
> Failed to apply plugin [id 'cz.malohlava']
   > Could not create plugin of type 'VisTaskExecGraphPlugin'.
      > org/gradle/execution/taskgraph/TaskInfo

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 29s
+ set +x
## Building client libs

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/ocouss/operatorFabric/operatorfabric-core/services/services.gradle' line: 32

* What went wrong:
A problem occurred evaluating project ':services'.
> Failed to apply plugin [id 'cz.malohlava']
   > Could not create plugin of type 'VisTaskExecGraphPlugin'.
      > org/gradle/execution/taskgraph/TaskInfo

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
## Building tools

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/ocouss/operatorFabric/operatorfabric-core/services/services.gradle' line: 32

* What went wrong:
A problem occurred evaluating project ':services'.
> Failed to apply plugin [id 'cz.malohlava']
   > Could not create plugin of type 'VisTaskExecGraphPlugin'.
      > org/gradle/execution/taskgraph/TaskInfo

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
## Building services

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/ocouss/operatorFabric/operatorfabric-core/services/services.gradle' line: 32

* What went wrong:
A problem occurred evaluating project ':services'.
> Failed to apply plugin [id 'cz.malohlava']
   > Could not create plugin of type 'VisTaskExecGraphPlugin'.
      > org/gradle/execution/taskgraph/TaskInfo

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
Oliviers-MacBook-Pro:operatorfabric-core ocouss$ clear

Oliviers-MacBook-Pro:operatorfabric-core ocouss$ bin/build_all.sh 
#### Building artifacts ####
# Using gradle options:   #
## Building swagger generator
+ gradle :tools:swagger-spring-generators:assemble

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/ocouss/operatorFabric/operatorfabric-core/services/services.gradle' line: 32

* What went wrong:
A problem occurred evaluating project ':services'.
> Failed to apply plugin [id 'cz.malohlava']
   > Could not create plugin of type 'VisTaskExecGraphPlugin'.
      > org/gradle/execution/taskgraph/TaskInfo

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
+ set +x
## Building client libs

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/ocouss/operatorFabric/operatorfabric-core/services/services.gradle' line: 32

* What went wrong:
A problem occurred evaluating project ':services'.
> Failed to apply plugin [id 'cz.malohlava']
   > Could not create plugin of type 'VisTaskExecGraphPlugin'.
      > org/gradle/execution/taskgraph/TaskInfo

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
## Building tools

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/ocouss/operatorFabric/operatorfabric-core/services/services.gradle' line: 32

* What went wrong:
A problem occurred evaluating project ':services'.
> Failed to apply plugin [id 'cz.malohlava']
   > Could not create plugin of type 'VisTaskExecGraphPlugin'.
      > org/gradle/execution/taskgraph/TaskInfo

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
## Building services

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/ocouss/operatorFabric/operatorfabric-core/services/services.gradle' line: 32

* What went wrong:
A problem occurred evaluating project ':services'.
> Failed to apply plugin [id 'cz.malohlava']
   > Could not create plugin of type 'VisTaskExecGraphPlugin'.
      > org/gradle/execution/taskgraph/TaskInfo

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

**Comment by francoisjolain** [comment] 2019-01-15 16:40
Hi, 

Thank you to participating to OperatorFabric development !

Sorry for the long delay, and sorry in advance for my response.
We have never try to build OperatorFabric on mac, because we don't have any mac in developer team.

I will see your issue with the core developer, maybe it's not just a mac issue. If, we currently can't reproduce your issue in linux, therefore we can't really fix it.

See you soon

**Comment by ocou-aprico** [comment] 2019-01-17 13:08
I confirm using gradle 5.x breaks the build process. 
Continuing to make running the platform....

**Comment by davidbinderRTE** [comment] 2019-01-17 13:31
I'm closing this one as there is a more accurate ticket for this problem (see #36)

**Closed by davidbinderRTE** 2019-01-17 13:31 UTC

**Comment by Rorschachdb** [comment] 2019-01-21 13:39
Hi, 

can you open a ticket for each problems (mac script support on one side, demo not working) and attach a complete log of thde mo docker compose to the latter ?

David.
